export * from "./client.model";
export * from "./clientAddress.model";
export * from "./clientCards.model";
export * from "./clientCompanyData.model";
export * from "./clientEmail.model";
export * from "./clientEmailNewsletter.model";
export * from "./clientEmailType.model";
export * from "./clientDeleted.model";
export * from "./clientMagicToken.model";
