import {
  mysqlTable,
  int,
  timestamp,
  varchar,
  mysqlEnum,
  double,
} from "drizzle-orm/mysql-core";

export const supplier = mysqlTable("fornecedor", {
  id_fornecedor: int("id_fornecedor").notNull().primaryKey(),
  nome: varchar("nome", { length: 250 }).notNull(),
  nome_fantasia: varchar("nome_fantasia", { length: 250 }).notNull(),
  cnpj: varchar("cnpj", { length: 100 }),
  cpf: varchar("cpf", { length: 100 }),
  inscricao_municipal: varchar("inscricao_municipal", { length: 100 }),
  inscricao_estadual: varchar("inscricao_estadual", { length: 100 }),
  contato: varchar("contato", { length: 100 }),
  prazo_pagamento: varchar("prazo_pagamento", { length: 100 }),
  id_fi_conta_contabil_depara_tipo: int("id_fi_conta_contabil_depara_tipo"),
  simples_nacional: mysqlEnum("simples_nacional", ["0", "1"]),
  id_fornecedor_ramo: int("id_fornecedor_ramo"),
  ramo: varchar("ramo", { length: 100 }),
  telefone: varchar("telefone", { length: 20 }),
  fax: varchar("fax", { length: 20 }),
  email: varchar("email", { length: 100 }),
  endereco: varchar("endereco", { length: 250 }),
  complemento: varchar("complemento", { length: 50 }),
  numero: int("numero"),
  bairro: varchar("bairro", { length: 50 }),
  cidade: varchar("cidade", { length: 50 }),
  estado: varchar("estado", { length: 2 }),
  cep: varchar("cep", { length: 20 }),
  obs: varchar("obs", { length: 20 }),
  banco: varchar("banco", { length: 20 }),
  agencia: varchar("agencia", { length: 20 }),
  conta: varchar("conta", { length: 20 }),
  ir: double("ir"),
  inss: double("inss"),
  pis: double("pis"),
  cofins: double("cofins"),
  iss_retem: mysqlEnum("iss_retem", ["0", "1"]),
  area: mysqlEnum("area", ["M", "T", "P", "F", "RH", "RY", "J", "A"]),
  created_at: timestamp("created_at", { mode: "string" }).defaultNow(),
  updated_at: timestamp("updated_at", { mode: "string" }).defaultNow(),
});
