export enum Permissions {
  PUBLIC_AUTHENTICATION_LOGIN = "authentication_login",
  PUBLIC_AUTHENTICATION_TOKEN = "authentication_token",
  PUBLIC_BANNER_VIEW = "banner_view",
  PUBLIC_CART_CREATE = "cart_create",
  PUBLIC_USER_VIEW = "user_view",
  PUBLIC_USER_CREATE = "user_create",
  PUBLIC_USER_UPDATE = "user_update",
  PUBLIC_USER_DELETE = "user_delete",
  PUBLIC_USER_UPDATE_PHONE = "user_update_phone",
  PUBLIC_USER_UPDATE_PASSWORD = "user_update_password",
  PUBLIC_USER_RECOVERY_PASSWORD = "user_recovery_password",
  PUBLIC_USER_VOUCHER = "user_voucher",
  PUBLIC_USER_ADDRESS_BILLING_VIEW = "user_address_billing_view",
  PUBLIC_USER_ADDRESS_SHIPPING_VIEW = "user_address_shipping_view",
  PUBLIC_USER_ADDRESS_BILLING_UPDATE = "user_address_billing_update",
  PUBLIC_USER_ADDRESS_SHIPPING_UPDATE = "user_address_shipping_update",
  PUBLIC_USER_IMAGE_UPDATE = "user_image_update",
  PUBLIC_USER_NEWSLETTER_SUBSCRIBE = "user_newsletter_subscribe",
}
