export enum TagSwagger {
  authentication = "authentication",
  user = "user",
  tfa = "tfa",
  banner = "banner",
  product = "product",
  plan = "plan",
  order = "order",
  voucher = "voucher",
  health = "health",
  cart = "cart",
  review = "review",
  webhook = "webhook",
  websocket = "websocket",
  newsletter = "newsletter",
}
