name: Validate JSON Files

on:
  pull_request:
    paths:
      - "packages/core/plugins/i18next/locales/en/translation.json"
      - "packages/core/plugins/i18next/locales/pt/translation.json"

env:
  VERSION_NODE: 20.11.1

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.VERSION_NODE }}

      - name: Install JSONLint
        run: npm install -g jsonlint

      - name: Validate JSON structure
        run: |
          jsonlint packages/core/plugins/i18next/locales/en/translation.json -q
          jsonlint packages/core/plugins/i18next/locales/pt/translation.json -q

      - name: Check for duplicate keys
        run: node .github/scripts/check-duplicates.js
