name: Validate JSON Files

on:
  pull_request:
    paths:
      - "packages/core/plugins/i18next/locales/en/translation.json"
      - "packages/core/plugins/i18next/locales/pt/translation.json"

env:
  VERSION_NODE: 20.11.1

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.VERSION_NODE }}

      - name: Install JSONLint and JSON Dup Key Validator
        run: |
          npm install jsonlint json-dup-key-validator
        working-directory: .github/scripts

      - name: Validate JSON structure
        run: |
          npx jsonlint ../../packages/core/plugins/i18next/locales/en/translation.json -q
          npx jsonlint ../../packages/core/plugins/i18next/locales/pt/translation.json -q
        working-directory: .github/scripts

      - name: Check for duplicate keys
        run: node check-duplicates.js
        working-directory: .github/scripts
